### PR TITLE
Initial version of APB

### PR DESCRIPTION
**Pull request by psturc**
### What is done in this PR
* provision, deprovision, test roles
* should meet requirements specified in https://issues.jboss.org/browse/AEROGEAR-8258 and https://issues.jboss.org/browse/AEROGEAR-8259
* more important/interesting stuff will be covered in the rest of tickets in [the sync app apb epic](https://issues.jboss.org/browse/AEROGEAR-8256)

### CODE REVIEW

**Comment by wtrocki** [comment]
@psturc Would be possible to create README that states:
- What environment variables should be used in image to setup database access
- Any other requirements for building image 

I'm happy to verify this later this week with the sample app we build. 
Really awesome work!

**Comment by wtrocki** [comment]
Actually I have noticed that we have this: https://issues.jboss.org/browse/AEROGEAR-8263
We can actually do that in Readme since docs it's still in progress.

**Comment by wtrocki** [comment]
+100 to get that into repo to not block work. There is ticket for end to end testing of the work so no verification needed. Work looks great!

**Comment by psturc** [comment]
@wtrocki @darahayes Thanks for review guys!

**Pull request merged**
